### ISSUE TITLE
Chargement FIL 21 + Refresh auto de l'interface (Non urgent )

### ISSUE THREAD

**Issue by mahdi6464** [lyxnter/DuetWebControl#33]
La machine est bloqué en occupé, aucune action possible à part restart duet

![Uploading MicrosoftTeams-image (2).png…]()

**Comment by ThomasCamguilhem** [comment]
Fixed in commit [e25dc44](https://github.com/lyxnter/MacroDuetS600D/commit/e25dc44b1b37807b4163617dcc88ed0979cfeee1) from MacroDuetS600D
