### ISSUE TITLE
Faire test reset factory 1.2.0 en sur un pc

### ISSUE THREAD

**Issue by mahdi6464** [lyxnter/DuetWebControl#42]
![Image](https://user-images.githubusercontent.com/69794662/227579539-3cd42e93-c1d0-43d2-9852-e6c7eccc6a86.png)

Après un reset factory par ce bouton sur la 243, rien ne se passe

![Image](https://user-images.githubusercontent.com/69794662/227579913-76c78ce8-8bf6-4269-b04c-ffee983b68d9.png)

**Comment by ThomasCamguilhem** [comment]
Bug identifié:
 présence d'un espace dans le nom du fichier (" FactoryReset_v1.2.0" vs "FactoryReset_v1.2.0")

**Comment by mahdi6464** [comment]
c'est bon pour la version anglaise

**Comment by mahdi6464** [comment]
C'est bon pour la version francaise
