### ISSUE TITLE
Changer webcontrol standard - pour prendre nouveau message erreur

### ISSUE THREAD

**Issue by mahdi6464** [lyxnter/DuetWebControl#43]

**Comment by mahdi6464** [comment]
Faire une branche special

**Comment by ThomasCamguilhem** [comment]
![Image](https://user-images.githubusercontent.com/44808748/231736531-03dcc585-8463-4a4c-b0a7-d111cd5faeb4.png)

**Comment by ThomasCamguilhem** [comment]
J'en ai profité pour améliorer la gestion des différents niveaux
