### ISSUE TITLE
3.4.5-LX.1 retour Louis Servel

### ISSUE THREAD

**Issue by mahdi6464** [lyxnter/DuetWebControl#71]
- Mettre la vignette de statut dans le bandeau supérieur afin que le statut soit visible de toutes les pages de l'interface
- Retirer Heater ,Current, Active, Stanby de LIQ21 et LIQ11
- Retirer Control heaters ( redondant )
- Espacement bordure pas constant
- Retirer Filament length sur le bandeau d'impression en cours
- Retirer filament usage de Job information
- Réduire Estimations et Collected Data  en seulement le temps estimé moyen et la durée d'impression
- Centrer la webcam
- Retirer dans Settings / Machine specific  -> tool temperature et spindle speed

**Comment by ThomasCamguilhem** [comment]
[] Mettre la vignette de statut dans le bandeau supérieur afin que le statut soit visible de toutes les pages de l'interface
[x] Retirer Heater ,Current, Active, Stanby de LIQ21 et LIQ11
[] Retirer Control heaters ( redondant )
[] Espacement bordure pas constant
[x] Retirer Filament length sur le bandeau d'impression en cours
[x] Retirer filament usage de Job information
[x] Réduire Estimations et Collected Data en seulement le temps estimé moyen et la durée d'impression
[] Centrer la webcam
[x] Retirer dans Settings / Machine specific -> tool temperature et spindle speed
